# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SudyingGit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CocoaLumberjack'
pod 'AFNetworking', '~> 3.0'
pod "OCMock"
  # Pods for SudyingGit

end
